Feature
Ispirett/tic-tac-toe pull request #1
Opened 2019-05-10 20:45 UTC by Ispirett

Thanks for your time.

2019-05-13 23:04 UTC, inhaq requested changes
Good work with folder structure and readme.
Update your game logic and try to separate your functions such that each function do one job. Also separate display messages from functionality.
I would recommend to have a look into `SOLID` and `OOP` concepts.
Once fixed, kindly resubmit for review.

2019-05-13 23:04 UTC, inhaq commented on lib/board.rb
>    def game_over?(_name = 'player')
winning logic is hardcoded

2019-05-14 16:43 UTC, Ispirett commented on lib/board.rb
>    def game_over?(_name = 'player')
thanks

2019-05-14 21:52 UTC, inhaq requested changes
Nice work on updating and fixing some changes requested. Although winning logic still seems to be hardcoded, you can implement it by loops.

2019-05-15 20:06 UTC, inhaq requested changes
Great work, the code looks good. The only concern is when I play the game and then restart with same player names/values as the previous game then it acts weirdly(means either it show winner name directly or it just quit). Let me know of your thinking behind this if you guys are doing deliberately or it's a bug?

2019-05-15 22:20 UTC, Macatuz commented
This should be a bug, cause is expected to get a new board each time you play a new game.

2019-05-16 00:35 UTC, Ispirett commented
Issue is fixed

2019-05-16 23:45 UTC, inhaq approved these changes
Great job, it's 👍🏻
In case I missed any issue, that'll be covered in tests. Go ahead and submit a project completion form.

2019-05-17 14:26 UTC, Ispirett commented
Thanks !!!!

2019-05-17 14:26 UTC, merged